import { COMPANY } from "./brand";

/** Escape a value for safe inline HTML. */
export function esc(value: unknown): string {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Open a clean, branded document in a new window and trigger the browser's
 * print dialog. Deliberately independent of the app chrome so an auditor gets
 * a company-letterhead printout (or PDF via "Save as PDF"), not a screenshot
 * of the UI. `bodyHtml` is the caller-built report markup (tables etc.).
 */
export function printDocument(title: string, subtitle: string, bodyHtml: string): void {
  const w = window.open("", "_blank", "width=980,height=1100");
  if (!w) {
    alert("Please allow pop-ups to print this document.");
    return;
  }
  const now = new Date().toLocaleString("en-GB", {
    day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit",
  });
  w.document.write(`<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${esc(title)} — ${esc(COMPANY.name)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Arial, sans-serif; color: #1b2a4a; margin: 0; padding: 32px 40px; }
  .head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #1b356b; padding-bottom: 14px; margin-bottom: 6px; }
  .co { font-size: 20px; font-weight: 800; color: #1b356b; }
  .co small { display: block; font-size: 12px; font-weight: 500; color: #5b6b8c; margin-top: 3px; }
  .meta { text-align: right; font-size: 11px; color: #5b6b8c; line-height: 1.6; }
  h1 { font-size: 17px; margin: 18px 0 2px; color: #12203d; }
  .sub { font-size: 12px; color: #5b6b8c; margin-bottom: 16px; }
  table { width: 100%; border-collapse: collapse; font-size: 12.5px; }
  th { text-align: left; background: #1b356b; color: #fff; padding: 8px 10px; font-weight: 600; }
  td { padding: 7px 10px; border-bottom: 1px solid #e4e8f0; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  tr.total td { font-weight: 700; border-top: 2px solid #1b356b; background: #f2f5fb; }
  tr.subhead td { font-weight: 700; background: #eef1f6; color: #1b356b; }
  tr.indent td:first-child { padding-left: 26px; }
  .foot { margin-top: 26px; display: flex; justify-content: space-between; font-size: 11px; color: #8792a8; border-top: 1px solid #e4e8f0; padding-top: 10px; }
  .sign { margin-top: 46px; display: flex; justify-content: space-between; font-size: 12px; }
  .sign div { width: 44%; border-top: 1px solid #1b2a4a; padding-top: 6px; text-align: center; color: #5b6b8c; }
  .pos { color: #1a7f4b; } .neg { color: #c0392b; }
  @page { margin: 14mm; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <div class="head">
    <div class="co">${esc(COMPANY.name)}<small>${esc(COMPANY.fullAddress)} · C.R ${esc(COMPANY.cr)}</small></div>
    <div class="meta">Currency: ${esc(COMPANY.currency)}<br/>VAT: 15%<br/>Printed: ${esc(now)}</div>
  </div>
  <h1>${esc(title)}</h1>
  <div class="sub">${esc(subtitle)}</div>
  ${bodyHtml}
  <div class="sign">
    <div>Prepared by</div>
    <div>Reviewed / Auditor</div>
  </div>
  <div class="foot"><span>${esc(COMPANY.name)}</span><span>Generated by ABID AK ERP · ${esc(now)}</span></div>
  <script>window.onload = function () { window.focus(); window.print(); };</script>
</body>
</html>`);
  w.document.close();
}

/** Format a number with thousands separators and 2 decimals (blank for zero). */
export function amt(value: number, blankZero = true): string {
  if (blankZero && !value) return "";
  return new Intl.NumberFormat("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);
}
